# Generated by Django 4.0.1 on 2022-06-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookiestand',
            old_name='average_cookies_per_sale',
            new_name='avgcookies',
        ),
        migrations.RenameField(
            model_name='cookiestand',
            old_name='hourly_sales',
            new_name='hourlySales',
        ),
        migrations.RenameField(
            model_name='cookiestand',
            old_name='maximum_customers_per_hour',
            new_name='maxCustomers',
        ),
        migrations.RenameField(
            model_name='cookiestand',
            old_name='minimum_customers_per_hour',
            new_name='minCustomers',
        ),
    ]
